Add onStartReached and onStartReachedThreshold props
Expensify/react-native pull request #17
Opened 2022-07-27 03:49 UTC by janicduplessis

I ported some minor fixes from https://github.com/Expensify/react-native/pull/8 and added a simpler example that just tests onStartReached instead of the one that tests maintainVisibleContentPosition too.

2022-07-31 04:39 UTC, roryabraham commented
Test results:

- [x] iOS w/o Fabric ✅ 
- [ ] iOS w/ Fabric ❌ 

    <img width="350" alt="image" src="https://user-images.githubusercontent.com/47436092/182010374-1c5c2895-18e2-45ea-a308-b234ec6bb2ae.png">

2022-07-31 06:20 UTC, roryabraham commented
The error that happens w/ Fabric starts [here](https://github.com/Expensify/react-native/blob/8f894e6652e59cec4b6e4dabca5a4ed98470bfe4/Libraries/Lists/VirtualizedList.js#L1603-L1606)

2022-07-31 06:21 UTC, roryabraham commented
Going to retest on `0.69-stable` to see if it's related to these changes.

2022-07-31 06:31 UTC, roryabraham requested changes
Unfortunately my testing has confirmed that the bug I found (on Fabric only) does not exist on `0.69-stable`, and is a regression caused by this code.

2022-08-03 22:45 UTC, janicduplessis commented
Looks like fabric has different timings and using initialScrollIndex doesn't work without passing getItemLayout. Adding this fixes the example.

2022-08-04 20:06 UTC, roryabraham approved these changes

2022-08-04 20:06 UTC, merged