Add support for numberOfLines and maximumNumberOfLines props on iOS and Android
Expensify/react-native pull request #37
Opened 2022-12-08 18:10 UTC by Szymon20000

## Summary

We want to be able to set height of TextArea/TextInput/EditText components on all platforms in the same way. Was is currently missing on iOS is expressing the height of a component in lines and this pr is supposed to fix it. Additionally in some cases we want to set maximum number of lines a "TextArea" like component can have. Because of Different screen sizes and accessibility settings it's sometimes hard to compute how many lines a current content takes so the purpose of `maximumNumberOfLines` prop is to simplify that process.

### iOS How it was implemented?
On Android the native "TextArea" like component (EditText) exposes `setLines` method that sets height of the component in lines. However, I wasn't able to find anything similar on iOS. What is a common method for both platforms is setting maximum height in lines. On iOS we can set `.maximumNumberOfLines` property on `TextContainer` and similarly on Android we can call `setMaxLines()` method to limit number of lines. So Adding `maximumNumberOfLines` is not a problem.   

I realised that when we add enough number of newLines in order to implement `numberOfLines` prop using `maximumNumberOfLines` functionality and did exactly that. Probably it's possible to get a font size and based on that set exact height but I didn't want to miss any edge cases and adding few newlines doesn't seem to be an overhead at all. 

### Android
I exposed `setMaxLines` in the same way `setLines` was exposed before so I'm pretty confident it's correct however I still need to test it.

### Fabric
In the new Arch measuring text seems to be exactly the same on the lowest level and I'm 99% sure it can be solved in the same way there. However, I still need to add this part to the pr. 

## Changelog

[CATEGORY] [TYPE] - Message

## Test Plan

- [ ] test iOS (Paper) 
- [ ] test iOS (Fabric) 
- [ ] test Android (Paper)
- [ ] test Android (Fabric)

2022-12-21 20:15 UTC, roryabraham requested changes
@Szymon20000 Sorry, but this PR needs to target a different branch, probably best to target https://github.com/Expensify/react-native/tree/Expensify-0.71.0-alpha1 for now. Thanks

2022-12-21 20:25 UTC, Szymon20000 commented
> @Szymon20000 Sorry, but this PR needs to target a different branch, probably best to target https://github.com/Expensify/react-native/tree/Expensify-0.71.0-alpha1 for now. Thanks

Not a problem. Will change that tomorrow morning. 
Can I already open the same pr in rn repo? Would like to know what rn core team thinks about those changes.

2022-12-21 20:28 UTC, roryabraham commented
> Can I already open the same pr in rn repo?

Totally, no reason to wait

2022-12-22 10:31 UTC, Szymon20000 commented
> 

Done

2022-12-22 10:37 UTC, Szymon20000 commented
This pr needs some polishing like clang-format but would like to first get some feedback on it.

2023-02-12 01:13 UTC, roryabraham requested changes
Apologies for the long delay in reviewing this @Szymon20000. Can you please update it to target the `Expensify-0.71.2-alpha.0` branch?

2023-02-13 17:32 UTC, Szymon20000 commented
> Apologies for the long delay in reviewing this @Szymon20000. Can you please update it to target the `Expensify-0.71.2-alpha.0` branch?

Sure, I will do it tomorrow morning together with renaming the prop as on 0.71 it's changed to "rows".

2023-02-14 12:33 UTC, Szymon20000 commented
Tested it after rebase and rename and it seems to works fine.

2023-02-16 03:27 UTC, roryabraham commented
@Szymon20000 Can you address the CI failures in the upstream plz?

2023-02-17 15:31 UTC, Szymon20000 commented
@roryabraham I tested it on Android and it looks like numberOfLines/rows doesn't work there properly. 
I checked and it's not caused by my changes. On new arch (Fabirc) `numberOfLines`/`rows` only set maximum number of lines the TextInput can have. However on old arch (paper) it sets fixed height in lines. However it looks like it does't set maximum limit so we can exceed number of lines we wanted to set. Do you want me to fix the issue also on Android? 
I tested it on RNTester on the main branch in upstream repo.

2023-02-17 15:32 UTC, Szymon20000 commented
Will do my best to fix CI failing tests later today.

2023-02-22 12:11 UTC, mountiny commented
> Do you want me to fix the issue also on Android? I tested it on RNTester on the main branch in upstream repo.

I imagine we would love to get this fixed on Android as well cc @roryabraham

2023-03-17 13:56 UTC, roryabraham approved these changes

2023-03-17 13:58 UTC, merged

2023-06-23 16:46 UTC, aimane-chnaif commented
Coming from https://github.com/Expensify/App/issues/17368:
This PR caused another bug in android - SVG icon inside Text isn't visible.
Hope new upstream [PR](https://github.com/facebook/react-native/pull/35703) will fix all known/unknown bugs including this one 🙏

2023-06-23 17:57 UTC, Szymon20000 commented
I believe the issue was already fixed by me and @roryabraham cherry-picked it. Probably the RN fork with the fix is not yet used in the app.

2023-06-23 18:06 UTC, aimane-chnaif commented
@Szymon20000 that's great! Can you please link that PR in our forked repo?

2023-06-23 18:30 UTC, Szymon20000 commented
I think that's the one https://github.com/Expensify/react-native/commit/dd492a1a3ed3a650ebb2ef6fe4ca46b328150526

2023-06-26 19:54 UTC, roryabraham commented
Just for clarity, we've since decided to drop our fork, use the upstream repo instead, and focus on getting PRs merged upstream.

2023-06-26 19:54 UTC, roryabraham commented
So we should be waiting on https://github.com/facebook/react-native/pull/38021 and https://github.com/facebook/react-native/pull/35703